name = "mppx-proxy"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[vars]
SOLANA_NETWORK = "devnet"
USDC_MINT = "2Cnsn4TLPWwPWZwQiLrurV8Ho33uCj1Md5RpTm7a6qsK"
